# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: send_message.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'send_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12send_message.proto\".\n\x11SendMessageStatus\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t\"2\n\x0csend_message\x12\"\n\x06status\x18\x01 \x01(\x0b\x32\x12.SendMessageStatus\"\xd5\x06\n\x11send_message_send\x12\x0e\n\x06msg_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63hat_id\x18\x03 \x01(\t\x12\x11\n\tchat_type\x18\x04 \x01(\x04\x12%\n\x04\x64\x61ta\x18\x05 \x01(\x0b\x32\x17.send_message_send.Data\x12\x14\n\x0c\x63ontent_type\x18\x06 \x01(\x04\x12\x12\n\ncommand_id\x18\x07 \x01(\x04\x12\x14\n\x0cquote_msg_id\x18\x08 \x01(\t\x12\'\n\x05media\x18\t \x01(\x0b\x32\x18.send_message_send.Media\x1a\xd3\x03\n\x04\x44\x61ta\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07\x62uttons\x18\x02 \x01(\t\x12\x11\n\tfile_name\x18\x04 \x01(\t\x12\x10\n\x08\x66ile_key\x18\x05 \x01(\t\x12\x14\n\x0cmentioned_id\x18\x06 \x03(\t\x12\x0c\n\x04\x66orm\x18\x07 \x01(\t\x12\x16\n\x0equote_msg_text\x18\x08 \x01(\t\x12\r\n\x05image\x18\t \x01(\t\x12\x0f\n\x07post_id\x18\n \x01(\t\x12\x12\n\npost_title\x18\x0b \x01(\t\x12\x14\n\x0cpost_content\x18\x0c \x01(\t\x12\x11\n\tpost_type\x18\r \x01(\t\x12\x17\n\x0fquote_image_url\x18\x10 \x01(\t\x12\x18\n\x10quote_image_name\x18\x11 \x01(\t\x12\x11\n\tfile_size\x18\x12 \x01(\x04\x12\r\n\x05video\x18\x13 \x01(\t\x12\r\n\x05\x61udio\x18\x15 \x01(\t\x12\x12\n\naudio_time\x18\x16 \x01(\x04\x12\x17\n\x0fquote_video_url\x18\x17 \x01(\t\x12\x18\n\x10quote_video_time\x18\x18 \x01(\x04\x12\x17\n\x0fsticker_item_id\x18\x19 \x01(\x04\x12\x17\n\x0fsticker_pack_id\x18\x1a \x01(\x04\x12\x11\n\troom_name\x18\x1d \x01(\t\x1a\xa5\x01\n\x05Media\x12\x10\n\x08\x66ile_key\x18\x01 \x01(\t\x12\x11\n\tfile_hash\x18\x02 \x01(\t\x12\x11\n\tfile_type\x18\x03 \x01(\t\x12\x14\n\x0cimage_height\x18\x05 \x01(\x04\x12\x13\n\x0bimage_width\x18\x06 \x01(\x04\x12\x11\n\tfile_size\x18\x07 \x01(\x04\x12\x11\n\tfile_key2\x18\x08 \x01(\t\x12\x13\n\x0b\x66ile_suffix\x18\t \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'send_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDMESSAGESTATUS']._serialized_start=22
  _globals['_SENDMESSAGESTATUS']._serialized_end=68
  _globals['_SEND_MESSAGE']._serialized_start=70
  _globals['_SEND_MESSAGE']._serialized_end=120
  _globals['_SEND_MESSAGE_SEND']._serialized_start=123
  _globals['_SEND_MESSAGE_SEND']._serialized_end=976
  _globals['_SEND_MESSAGE_SEND_DATA']._serialized_start=341
  _globals['_SEND_MESSAGE_SEND_DATA']._serialized_end=808
  _globals['_SEND_MESSAGE_SEND_MEDIA']._serialized_start=811
  _globals['_SEND_MESSAGE_SEND_MEDIA']._serialized_end=976
# @@protoc_insertion_point(module_scope)
