# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: conversation.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'conversation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63onversation.proto\"#\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x9b\x04\n\x04list\x12\x17\n\x06status\x18\x01 \x01(\x0b\x32\x07.Status\x12\x18\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\n.list.Data\x12\r\n\x05total\x18\x03 \x01(\x04\x12\x12\n\nrequest_id\x18\x04 \x01(\t\x1a\xbc\x03\n\x04\x44\x61ta\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\t\x12\x11\n\tchat_type\x18\x02 \x01(\x04\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0c\x63hat_content\x18\x04 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x04\x12\x16\n\x0eunread_message\x18\x06 \x01(\x04\x12\n\n\x02\x61t\x18\x07 \x01(\x04\x12\x11\n\tavatar_id\x18\x08 \x01(\x04\x12\x12\n\navatar_url\x18\t \x01(\t\x12\x16\n\x0e\x64o_not_disturb\x18\x0b \x01(\x04\x12\x11\n\ttimestamp\x18\x0c \x01(\x04\x12#\n\x07\x61t_data\x18\x0e \x01(\x0b\x32\x12.list.Data.At_data\x12\x1b\n\x13\x63\x65rtification_level\x18\x10 \x01(\x04\x1a\x9d\x01\n\x07\x41t_data\x12\x0f\n\x07unknown\x18\x01 \x01(\x04\x12\x14\n\x0cmentioned_id\x18\x02 \x01(\t\x12\x16\n\x0ementioned_name\x18\x03 \x01(\t\x12\x14\n\x0cmentioned_in\x18\x04 \x01(\t\x12\x14\n\x0cmentioner_id\x18\x06 \x01(\t\x12\x16\n\x0ementioner_name\x18\x07 \x01(\t\x12\x0f\n\x07msg_seq\x18\x08 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'conversation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=22
  _globals['_STATUS']._serialized_end=57
  _globals['_LIST']._serialized_start=60
  _globals['_LIST']._serialized_end=599
  _globals['_LIST_DATA']._serialized_start=155
  _globals['_LIST_DATA']._serialized_end=599
  _globals['_LIST_DATA_AT_DATA']._serialized_start=442
  _globals['_LIST_DATA_AT_DATA']._serialized_end=599
# @@protoc_insertion_point(module_scope)
