name: Advanced Build

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Target runtime'
        required: true
        default: 'win-x64'
        type: choice
        options:
        - win-x64
        - win-x86
        - linux-x64
        - osx-x64

jobs:
  build:
    runs-on: ${{ fromJSON('{"win-x64":"windows-latest","win-x86":"windows-latest","linux-x64":"ubuntu-latest","osx-x64":"macos-latest"}')[github.event.inputs.runtime] }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
        
    - name: Build and Publish
      run: |
        dotnet publish \
          --configuration Release \
          --runtime ${{ github.event.inputs.runtime }} \
          --self-contained true \
          -p:PublishSingleFile=true \
          -p:DebugType=embedded \
          -p:DebugSymbols=false \
          -p:IncludeAllContentForSelfExtract=true \
          --output ./dist
          
    - name: Display file info
      run: |
        ls -la ./dist/
        echo "File size:"
        du -h ./dist/* | head -n 1
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-${{ github.event.inputs.runtime }}
        path: ./dist/